apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: ang11
spec:
  selector:
    matchLabels:
      app: ang11
  replicas: 1 # tells deployment to run 1 pod matching the template
  template:
    metadata:
      labels:
        app: ang11
    spec:
      containers:
      - name: simpleapi
        image: sogetislbdemo.azurecr.io/angll:v1
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "1"
            memory: "200Mi"
          requests:
            cpu: "0.1"
            memory: "100Mi"
---
kind: Service
apiVersion: v1
metadata:
  name: ang11
spec:
  selector:
    app: ang11
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer